-- Query the list of CITY names from STATION that do not start or end with vowels (case-insensitive).
-- Exclude duplicates.

SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT LIKE 'a%' 
  AND LOWER(CITY) NOT LIKE 'e%' 
  AND LOWER(CITY) NOT LIKE 'i%' 
  AND LOWER(CITY) NOT LIKE 'o%' 
  AND LOWER(CITY) NOT LIKE 'u%'
  AND LOWER(CITY) NOT LIKE '%a' 
  AND LOWER(CITY) NOT LIKE '%e' 
  AND LOWER(CITY) NOT LIKE '%i' 
  AND LOWER(CITY) NOT LIKE '%o' 
  AND LOWER(CITY) NOT LIKE '%u';


-- 
-- SELECT DISTINCT CITY
-- FROM STATION
-- WHERE CITY NOT LIKE 'A%' AND CITY NOT LIKE 'a%'
--   AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'e%'
--   AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'i%'
--   AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'o%'
--   AND CITY NOT LIKE 'U%' AND CITY NOT LIKE 'u%'
--   AND CITY NOT LIKE '%A' AND CITY NOT LIKE '%a'
--   AND CITY NOT LIKE '%E' AND CITY NOT LIKE '%e'
--   AND CITY NOT LIKE '%I' AND CITY NOT LIKE '%i'
--   AND CITY NOT LIKE '%O' AND CITY NOT LIKE '%o'
--   AND CITY NOT LIKE '%U' AND CITY NOT LIKE '%u';
-- 
